2023-04-13 22:10:23,449 : INFO : root : Loading config.
2023-04-13 22:10:23,449 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2023-04-13 22:10:23,449 : INFO : ConfigProcessor : Loading config from cache: C:\Users\digidev\AppData\Local\Temp\02a419de2b33454b673806682c00b740.mpf_cache
2023-04-13 22:10:23,542 : INFO : ConfigProcessor : Loading config from cache: C:\Users\digidev\AppData\Local\Temp\e10c931dc18d80379143a09443f0855e.mpf_cache
2023-04-13 22:10:23,542 : INFO : ConfigProcessor : Loading config from cache: C:\Users\digidev\AppData\Local\Temp\dfc215c2101357f1268429d195cf05eb.mpf_cache
2023-04-13 22:10:23,558 : INFO : Machine : Mission Pinball Framework Core Engine v0.55.0
2023-04-13 22:10:23,558 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs\\2023-04-13-22-10-23-mpf-DESKTOP-JGO3PQG.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2023-04-13 22:10:23,558 : INFO : Machine : MPF path: c:\users\digidev\appdata\local\programs\python\python37\lib\site-packages\mpf
2023-04-13 22:10:23,558 : INFO : Machine : Machine path: C:\Users\digidev\source\Pinball_Three-Amigos
2023-04-13 22:10:23,558 : INFO : Machine : Platform: win32
2023-04-13 22:10:23,558 : INFO : Machine : Python executable location: c:\users\digidev\appdata\local\programs\python\python37\python.exe
2023-04-13 22:10:23,558 : INFO : Machine : Python version: 3.7.9 (64-bit)
2023-04-13 22:10:23,558 : INFO : Machine : Initialise MPF.
2023-04-13 22:10:23,621 : ERROR : Machine : Failed to initialise MPF
Traceback (most recent call last):
  File "c:\users\digidev\appdata\local\programs\python\python37\lib\site-packages\mpf\platforms\p_roc_common.py", line 31, in <module>
    import pinproc
ModuleNotFoundError: No module named 'pinproc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\digidev\appdata\local\programs\python\python37\lib\site-packages\mpf\platforms\p_roc_common.py", line 39, in <module>
    from mpf.platforms.pinproc.windows import pinproc
ImportError: DLL load failed: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\digidev\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 673, in initialise_mpf
    raise init.exception()
  File "c:\users\digidev\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 244, in initialise
    await self.initialise_core_and_hardware()
  File "c:\users\digidev\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 230, in initialise_core_and_hardware
    self._load_hardware_platforms()
  File "c:\users\digidev\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 473, in _load_hardware_platforms
    self.add_platform(hardware_platform)
  File "c:\users\digidev\appdata\local\programs\python\python37\lib\site-packages\mpf\core\machine.py", line 607, in add_platform
    self.hardware_platforms[name] = hardware_platform(self)
  File "c:\users\digidev\appdata\local\programs\python\python37\lib\site-packages\mpf\platforms\p3_roc.py", line 107, in __init__
    super().__init__(machine)
  File "c:\users\digidev\appdata\local\programs\python\python37\lib\site-packages\mpf\platforms\p_roc_common.py", line 183, in __init__
    'hardware in the meantime.', 3, 'P-Roc') from IMPORT_ERROR
mpf.exceptions.runtime_error.MpfRuntimeError: Runtime Error in P-Roc: Could not import "pinproc". Either the library is not installed or is missing some of its dependencies. Check the install instructions for your OS in Multimorphic section of the MPF docs. You can run mpf with "-X" to use virtual hardware in the meantime. Error Code: RE-P-Roc-3 (https://docs.missionpinball.org/en/0.55/logs/RE-P-Roc-3.html)
